[SNAPSHOT]
snapshot_interval_minutes = 10
compress_state = True

[MASKING]
masking = [
          {"regex_pattern": "\\b[a-zA-Z0-9_]+-[a-zA-Z0-9_]+-[a-zA-Z0-9_]+\\b", "mask_with": "EQUIPMENT_ID"},
          {"regex_pattern": "(?<![A-Za-z0-9])[\\-\\+]?\\d+\\.\\d+(?![A-Za-z0-9])", "mask_with": "FLOAT"},
          {"regex_pattern": "(?<![A-Za-z0-9])[\\-\\+]?\\d+(?![A-Za-z0-9.])", "mask_with": "NUM"},
          {"regex_pattern": "0[xX][0-9a-fA-F]+", "mask_with": "HEX"},
          {"regex_pattern": "(?<=[:=] )[^\\s,;]+", "mask_with": "VAL"}
          ]
mask_prefix = <:
mask_suffix = :>

[DRAIN]
# engine is Optional parameter. Engine will be "Drain" if the engine argument is not specified.
# engine has two options: 'Drain' and 'JaccardDrain'.
# engine = Drain
sim_th = 0.4
depth = 4
max_children = 100
max_clusters = 1024
extra_delimiters = ["_"]

[PROFILING]
enabled = True
report_sec = 30